"""Launch a reproducible real-provider smoke job on Kaggle GPU.

The Kaggle credential is read only from KAGGLE_API_TOKEN/KAGGLE_API_KEY.
No credential, model weights, or runtime media is stored in the repository.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import tempfile
from pathlib import Path


def _token() -> str:
    token = os.getenv("KAGGLE_API_TOKEN") or os.getenv("KAGGLE_API_KEY")
    if not token:
        raise RuntimeError("Kaggle credential missing: set KAGGLE_API_TOKEN or KAGGLE_API_KEY")
    return token


def _kaggle() -> list[str]:
    _token()
    return ["kaggle"]


def build_notebook(video_url: str, repo: str, ref: str, profile: str) -> dict:
    """Build notebook metadata/code without embedding secrets."""
    code = f'''# Generated by kaggle_gpu_orchestrator.py\n\n!git clone --depth 1 --branch {ref} https://github.com/{repo}.git /kaggle/working/repo\n%cd /kaggle/working/repo\n!pip install -r requirements.txt\n!pip install -r requirements-cloud-runner.txt\n!python run_cloud_smoke.py "{video_url}" --output validation-input/source.mp4\n!python real_provider_runner.py demucs --audio validation-input/source.mp4 --work provider-validation-work\n\n# MediaPipe and Wav2Lip remain explicit provider profiles; execute only after\n# their runtime prerequisites/checkpoints are installed in this notebook.\nprint("profile={profile}")\n'''
    return {"metadata": {"profile": profile, "repo": repo, "ref": ref}, "code": code}


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare/launch a Kaggle GPU provider smoke job")
    parser.add_argument("--video-url", required=True)
    parser.add_argument("--repo", default="ajfaysal/smart-ai-social-automation-agent")
    parser.add_argument("--ref", default="main")
    parser.add_argument("--profile", choices=("demucs", "full"), default="full")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    notebook = build_notebook(args.video_url, args.repo, args.ref, args.profile)
    if args.dry_run:
        print(json.dumps(notebook, indent=2))
        return 0

    # Keep the API credential out of argv, notebook text, logs, and repository files.
    _token()
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "provider_smoke.ipynb"
        path.write_text(json.dumps(notebook, ensure_ascii=False, indent=2), encoding="utf-8")
        result = subprocess.run([*_kaggle(), "kernels", "push", "-p", tmp], check=False)
        return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
