"""Build a Kaggle GPU notebook for the real end-to-end dubbing smoke run."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def build_notebook(video_url: str, repo: str, ref: str, language: str = "Bangla") -> dict:
    source = f'''import json, os, shutil, subprocess
from pathlib import Path

REPO = Path("/kaggle/working/repo")
INPUT = REPO / "validation-input" / "source.mp4"
ARTIFACTS = Path("/kaggle/working/final-artifacts")
ARTIFACTS.mkdir(parents=True, exist_ok=True)

try:
    from kaggle_secrets import UserSecretsClient
    secrets = UserSecretsClient()
    def secret(name, required=False):
        try:
            value = secrets.get_secret(name)
        except Exception:
            value = ""
        if required and not value:
            raise RuntimeError(f"Missing Kaggle Secret: {{name}}")
        return value
except Exception:
    def secret(name, required=False):
        value = os.getenv(name, "")
        if required and not value:
            raise RuntimeError(f"Missing runtime secret: {{name}}")
        return value
'''
    # The full notebook source is generated by the canonical pipeline below.
    source += f'''\nVIDEO_URL = {video_url!r}\nREPO_URL = {repo!r}\nREPO_REF = {ref!r}\nTARGET_LANGUAGE = {language!r}\n\nsubprocess.run(["git", "clone", "--depth", "1", "--branch", REPO_REF, REPO_URL, str(REPO)], check=True)\n\n# Canonical pipeline/runtime requirements.\nsubprocess.run(["python", "-m", "pip", "install", "-q", "-r", str(REPO / "requirements.txt")], check=True)\nsubprocess.run(["python", "-m", "pip", "install", "-q", "edge-tts>=7,<8"], check=True)\n\n# Runtime-only credentials/model URLs are read from Kaggle Secrets.\nos.environ["OPENAI_API_KEY"] = secret("OPENAI_API_KEY", required=True)\nos.environ["WAV2LIP_CHECKPOINT_URL"] = secret("WAV2LIP_CHECKPOINT_URL", required=True)\nos.environ["WAV2LIP_S3FD_URL"] = secret("WAV2LIP_S3FD_URL", required=True)\nos.environ["LIPSYNC_PROVIDER"] = "wav2lip"\nos.environ["FACE_DETECTOR"] = "opencv-haar"\nos.environ["MOUTH_LANDMARK_PROVIDER"] = "mediapipe"\n\nfrom cloud_video_input import download_cloud_video\nfrom drama_dubbing import dub_video\n\nINPUT.parent.mkdir(parents=True, exist_ok=True)\ndownload_cloud_video(VIDEO_URL, INPUT)\nfinal_path, manifest_path, srt_path, report_path = dub_video(\n    INPUT, TARGET_LANGUAGE, requested_voice="auto",\n    preserve_background=False, add_mood_music=False, lip_sync=True,\n    output_dir=ARTIFACTS\n)\nprint(json.dumps({{"final": str(final_path), "manifest": str(manifest_path), "srt": str(srt_path), "report": str(report_path)}}, ensure_ascii=False, indent=2))\n'''
    return {
        "cells": [{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source.splitlines(True)}],
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python"}},
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("video_url")
    parser.add_argument("--repo", default="ajfaysal/smart-ai-social-automation-agent")
    parser.add_argument("--ref", default="main")
    parser.add_argument("--language", default="Bangla", choices=["Bangla", "English", "Hindi"])
    parser.add_argument("--output", default="kaggle_full_pipeline.ipynb")
    args = parser.parse_args()
    notebook = build_notebook(args.video_url, args.repo, args.ref, args.language)
    Path(args.output).write_text(json.dumps(notebook, ensure_ascii=False, indent=2), encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
